### PR TITLE
Updated to work with serverless-plugin-split-stacks.

### PR DESCRIPTION
**Pull request by tfendt**
Adds ApiGatewayRestApiId to stack output. If rest api id is not found as part of the originally programmed method then it checks the output variables.
This fix is regarding #8 issue.

### CODE REVIEW

**Comment by tfendt** [comment]
@MikeSouza Could I get a merge/review on this?

**Comment by MikeSouza** [comment]
I’ll take a look this weekend. Thanks.

**Comment by MikeSouza** [comment]
I don't have much time to review and test this thoroughly. I don't use this particular split stacks plugin. Have you tested that the plugin still works as originally intended without the use of this split stacks plugin and that your changes do not break the original existing functionality?

**Comment by tfendt** [comment]
> @tfendt I don't have much time to test this since I don't use this particular split stacks plugin. Have you tested that the plugin still works as originally intended without the use of this split stacks plugin and that your changes do not break the original existing use case/ functionality?
> 
> Also, coverage has now decreased to from 100% to 96.61%. Please ensure 100% test coverage.

Yes, I have tested without the split stacks plugin. The new code leaves your existing code in place and adds an additional check if the RestApiId is not found.

**Comment by MikeSouza** [comment]
Ok thanks. If you can please get the test coverage back to 100%, I can
merge.

**Comment by tfendt** [comment]
@MikeSouza updated with 100% test coverage.

**Pull request merged**
